/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motorph.v4;

import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KrisChan
 */
public class PayrollStaffDB extends javax.swing.JFrame {

    /**
     * Creates new form PayrollStaffDB
     */
    public PayrollStaffDB() {
        initComponents();
        loadEmployeeData();
        setLocationRelativeTo(null);
        loadPayrollData();
    }
    
    private void loadEmployeeData() {
        DefaultTableModel model = (DefaultTableModel) employee_data.getModel();
        model.setRowCount(0); // Clear existing data

        ResultSet rs = Database.getAllEmployees();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("employee_id"),
                    rs.getString("last_name"),
                    rs.getString("first_name"),
                    rs.getString("birthday"), // Converts SQL Date to Java Date
                    rs.getString("address"),
                    rs.getString("phone_number"),
                    rs.getString("status"),
                    rs.getString("position"),
                    rs.getString("department"),
                    rs.getString("supervisor"),
                    rs.getInt("basic_salary"),
                   
                    
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading employee data: " + e.getMessage());
        }
    }
    
    
    private void loadPayrollData() {
        DefaultTableModel model = (DefaultTableModel) payrollData.getModel();
        model.setRowCount(0); // Clear existing data

        ResultSet rs = Database.getPayrollDetails();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("date"),
                    rs.getString("employee_id"),
                    rs.getString("hourly_rate"), 
                    rs.getString("working_hours"),
                    rs.getString("overtime_hours"),
                    rs.getString("deductions"),
                    rs.getString("net_salary")
                   
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading employee data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewEmp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        processPayroll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        empData = new javax.swing.JScrollPane();
        employee_data = new javax.swing.JTable();
        processPayrollPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        payrollData = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        txtSSS = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        txtHrsWorked = new javax.swing.JTextField();
        txtOvertime = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        txtTIN = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        txtPagibig = new javax.swing.JTextField();
        txtPhilhealth = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        lblNetSalary = new java.awt.Label();
        label13 = new java.awt.Label();
        lblRate = new java.awt.Label();
        btnPP = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        lblDeductions = new java.awt.Label();
        label12 = new java.awt.Label();
        lblgrossSalary = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAYROLL DASHBOARD");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewEmp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        viewEmp.setText("View Employees");
        viewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmpActionPerformed(evt);
            }
        });
        jPanel1.add(viewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 40));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, 40));

        processPayroll.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        processPayroll.setText("Process Payroll");
        processPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processPayrollActionPerformed(evt);
            }
        });
        jPanel1.add(processPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        parentPanel.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        employee_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        employee_data.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] { "Employee ID", "Last Name", "First Name", "Birth Date", "Address", "Phone Number", "Status", "Position", "Department", "Supervisor",
                "Basic Salary"}
        ));
        empData.setViewportView(employee_data);

        parentPanel.add(empData, "card2");

        processPayrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        processPayrollPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payrollData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Employee ID", "Hourly Rate", "Hours Worked", "Overtime", "Deductions", "Net Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(payrollData);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 240));

        processPayrollPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 720, 240));

        label1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 0, 153));
        label1.setName(""); // NOI18N
        label1.setText("SSS");
        processPayrollPanel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        label2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(153, 0, 153));
        label2.setText("Date");
        processPayrollPanel.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        label3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 0, 153));
        label3.setText("Employee ID");
        processPayrollPanel.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        label5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(153, 0, 153));
        label5.setText("Rate");
        processPayrollPanel.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        label6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(153, 0, 153));
        label6.setText("Hours Worked");
        processPayrollPanel.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        label7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(153, 0, 153));
        label7.setText("Overtime");
        processPayrollPanel.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtSSS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, -1));

        txtDate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, -1));

        txtEmpID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        txtHrsWorked.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtHrsWorked, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        txtOvertime.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        label8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(153, 0, 153));
        label8.setText("Philhealth");
        processPayrollPanel.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        label9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(153, 0, 153));
        label9.setText("TIN");
        processPayrollPanel.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtTIN.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 130, -1));

        label10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(153, 0, 153));
        label10.setText("Net Salary");
        processPayrollPanel.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        txtPagibig.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtPagibig, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, -1));

        txtPhilhealth.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        processPayrollPanel.add(txtPhilhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, -1));

        label11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label11.setForeground(new java.awt.Color(153, 0, 153));
        label11.setText("PAGIBIG");
        processPayrollPanel.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        lblNetSalary.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNetSalary.setForeground(new java.awt.Color(0, 0, 0));
        processPayrollPanel.add(lblNetSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, -1));

        label13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(153, 0, 153));
        label13.setText("Deductions");
        processPayrollPanel.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        lblRate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblRate.setForeground(new java.awt.Color(0, 0, 0));
        processPayrollPanel.add(lblRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, -1));

        btnPP.setText("Process Payroll");
        btnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPActionPerformed(evt);
            }
        });
        processPayrollPanel.add(btnPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 83, 150, 30));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        processPayrollPanel.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 150, 30));

        lblDeductions.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDeductions.setForeground(new java.awt.Color(0, 0, 0));
        processPayrollPanel.add(lblDeductions, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, -1));

        label12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        label12.setForeground(new java.awt.Color(153, 0, 153));
        label12.setText("Gross Salary");
        processPayrollPanel.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblgrossSalary.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblgrossSalary.setForeground(new java.awt.Color(0, 0, 0));
        processPayrollPanel.add(lblgrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, -1));

        parentPanel.add(processPayrollPanel, "card3");

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 740, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        dispose(); // Close current dashboard
        new LoginForm().setVisible(true); // Return to login screen
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmpActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(empData);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_viewEmpActionPerformed

    private void processPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processPayrollActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(processPayrollPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_processPayrollActionPerformed

    private void btnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPActionPerformed
        // TODO add your handling code here:
    String date = txtDate.getText().trim();
    String employeeId = txtEmpID.getText().trim();

    if (date.isEmpty() || employeeId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Date and Employee ID cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double hourlyRate = Double.parseDouble(lblRate.getText());
        int hoursWorked = Integer.parseInt(txtHrsWorked.getText());
        int overtimeHours = Integer.parseInt(txtOvertime.getText());
        double deductions = Double.parseDouble(lblDeductions.getText());
        double netSalary = Double.parseDouble(lblNetSalary.getText());

        boolean success = Database.insertPayrollRecord(date, employeeId, hourlyRate, hoursWorked, overtimeHours, deductions, netSalary);

        if (success) {
            JOptionPane.showMessageDialog(this, "Payroll processed successfully!");
            loadPayrollData(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error processing payroll.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnPPActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        String employeeId = txtEmpID.getText().trim();
        if (employeeId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an Employee ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double hourlyRate = Database.getHourlyRate(employeeId);
    
    if (hourlyRate > 0) {
        lblRate.setText(String.format("%.2f", hourlyRate)); // Display the rate
    } else {
        JOptionPane.showMessageDialog(this, "Employee not found or has no hourly rate.", "Search Error", JOptionPane.ERROR_MESSAGE);
        lblRate.setText(""); 
    }
            
        
        double sss = Double.parseDouble(txtSSS.getText());
        double philhealth = Double.parseDouble(txtPhilhealth.getText());
        double tin = Double.parseDouble(txtTIN.getText());
        double pagibig = Double.parseDouble(txtPagibig.getText());
        double hrsWorked= Double.parseDouble(txtHrsWorked.getText());
        double overtime= Double.parseDouble(txtOvertime.getText());        
        double rate= Double.parseDouble(lblRate.getText());        
                
                
        double deductions= sss+philhealth+tin+pagibig;
        double grossSalary= rate* (hrsWorked+overtime);
        double netSalary= grossSalary-deductions;
        
        
        lblRate.setText(String.format("%.2f", hourlyRate));
        lblNetSalary.setText(String.format("%.2f", netSalary));
        lblDeductions.setText(String.format("%.2f", deductions));
        lblgrossSalary.setText(String.format("%.2f", grossSalary));
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollStaffDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollStaffDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollStaffDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollStaffDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollStaffDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnPP;
    private javax.swing.JScrollPane empData;
    private javax.swing.JTable employee_data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblDeductions;
    private java.awt.Label lblNetSalary;
    private java.awt.Label lblRate;
    private java.awt.Label lblgrossSalary;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTable payrollData;
    private javax.swing.JButton processPayroll;
    private javax.swing.JPanel processPayrollPanel;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtHrsWorked;
    private javax.swing.JTextField txtOvertime;
    private javax.swing.JTextField txtPagibig;
    private javax.swing.JTextField txtPhilhealth;
    private javax.swing.JTextField txtSSS;
    private javax.swing.JTextField txtTIN;
    private javax.swing.JButton viewEmp;
    // End of variables declaration//GEN-END:variables
}
